# Generated by Django 4.0 on 2021-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_status_tutor_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.ManyToManyField(to='home.Subject'),
        ),
    ]
