# Generated by Django 4.0 on 2021-12-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tutor_subject_tutor_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, null=True)),
                ('book_hours', models.IntegerField(default='')),
                ('book_days', models.IntegerField(default='')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tutor')),
            ],
        ),
    ]
