# Generated by Django 4.0 on 2021-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookupdate_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
